## Configuration data
config = {
    "cvs_sites": ['BOSTON', 'SOMERVILLE', 'DORCHESTER', 'BRIGHTON', 'BROOKLINE', 'CAMBRIDGE', 'MEDFORD', 'ARLINGTON', 'MALDEN', 'WATERTOWN', 'WALTHAM', 'WESTFORD', 'ACTON', 'MAYNARD', 'CONCORD', 'LEOMINSTER']
}


