## Configuration data
config = {
    "cvs_sites": ['MEDFORD', 'DANVERS', 'GLOUCESTER', 'LYNN', 'MEDFORD', 'READING', 'SAUGUS', 'SOMERVILLE', 'STONEHAM', 'WINCHESTER', 'WOBURN', 'MARBLEHEAD', 'MARLBOROUGH', 'FRAMINGHAM', 'WESTBOROUGH', 'REVERE', 'ARLINGTON', 'MALDEN', 'PEABODY', 'WORCESTER', 'LOWELL', 'DRACUT', 'BILLERICA', 'WILMINGTON', 'METHUEN']
}
